### ISSUE TITLE
Integrate Fuzzy search

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticore-github-issue-search#20]
We should add the latest update from Buddy to work with the Manticore GitHub demo. This will allow us to validate its quality on a large dataset and assess how fast it is. 

The purpose of this integration is to use the latest version of Buddy and make fuzzy search the default for keyword-type searches.

**Comment by donhardman** [comment]
The integration is complete. If everything works well from the client's perspective, further improvements will focus on the Fuzzy-related tasks in Buddy.

**Comment by sanikolaev** [comment]
Done.
