### ISSUE TITLE
Improve query suggestions UI

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticore-github-issue-search#22]
We should move forward with enhancing the query suggestions panel and make it respond to the up and down arrow keys just like Google does. When users press the up or down arrows, it should set a new phrase in the input field and also change the focus accordingly.

<img width="445" alt="image" src="https://github.com/user-attachments/assets/9a72ab98-9133-44d0-a7a3-4075ea790e6d">

**Comment by donhardman** [comment]
Implemented: https://github.com/manticoresoftware/manticore-github-issue-search/pull/21

**Comment by sanikolaev** [comment]
Thanks. LGTM!
