### ISSUE TITLE
Long query leads to "Something went wrong"

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticore-github-issue-search#33]
When we input a very long query and use Fuzzy matching, we are experiencing a "Something went wrong" error. We should investigate this issue.

An example of this is: https://github.manticoresearch.com/manticoresoftware/manticoresearch?query=after+daemon+stopped+executer+left++on+linux+after+daemon+got+stopped+the+manticore-executor+left+in+the+background.+The+daemon+should+seng+SIGTERM+signal+to+buddy+process+instead+of+the+SIGKILL&filters%5Bcomment%5D%5B%5D=28798446&filters%5Bcommon%5D%5Brepo_id%5D%5B%5D=95614931&sort=&search=keyword-search-fuzzy-layouts

**Comment by sanikolaev** [comment]
As discussed, we want to introduce a new flag for the fuzzy search / autocomplete functionality to control the behaviour when an unknown word is provided by the user.

**Comment by donhardman** [comment]
All fixes as discussed were implemented in these pull requests:
- https://github.com/manticoresoftware/buddy-core/pull/74
- https://github.com/manticoresoftware/manticoresearch-buddy/pull/362

**Comment by donhardman** [comment]
@Nick-S-2018 please review pull request, so we can proceed with merging

**Comment by Nick-S-2018** [comment]
Done

**Comment by donhardman** [comment]
It was merged to the main of Buddy, closing this issue.
