### ISSUE TITLE
Add license and fix indexers

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticore-github-issue-search#38]
We need to address the following issues:
1. Add the missing license
2. Investigate indexer issues as something is malfunctioning
3. Optimize frontend performance by implementing lazy loading for images
4. Add multiple repo links on the main page after search input

**Comment by donhardman** [comment]
All updates for Github Issue Search were merged.
Updates for image search demo: https://github.com/manticoresoftware/manticore-image-search/pull/1

**Comment by sanikolaev** [comment]
Requested changes in the PR.

**Comment by donhardman** [comment]
Fixed in the PR

**Comment by sanikolaev** [comment]
Requested one change in the [PR](https://github.com/manticoresoftware/manticore-image-search/pull/1)

**Comment by sanikolaev** [comment]
All merged.
